name: map_controller_plus_3
description: A map controller for Flutter map v3.0.0. Manage markers, lines and polygons.
homepage: https://github.com/makesappy
repository: https://github.com/makesappy/map_controller_plus_3
version: 1.0.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  geojson: ^1.0.0
  geopoint: ^1.0.0
  latlong2: ^0.8.1
  rxdart: ^0.27.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  meta: ^1.7.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
